// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Report
 */
export type Report = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    report_type: ReportType;
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    /**
     * Description
     */
    description: string;
    /**
     * Creation Time
     */
    creation_time: string;
};

/**
 * ReportCreation
 */
export type ReportCreation = {
    /**
     * Title
     */
    title: string;
    report_type: ReportType;
    /**
     * Location
     */
    location: {
        [key: string]: unknown;
    };
    /**
     * Description
     */
    description: string;
};

/**
 * ReportEdit
 */
export type ReportEdit = {
    /**
     * Title
     */
    title: string | null;
    report_type: ReportType | null;
    /**
     * Location
     */
    location: {
        [key: string]: unknown;
    } | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Last Updated Time
     */
    last_updated_time: string;
};

/**
 * ReportStatus
 */
export type ReportStatus = 'pending_review' | 'active' | 'resolved' | 'archived' | 'rejected';

/**
 * ReportType
 */
export type ReportType = 'highlight' | 'danger' | 'problem';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetReportsTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports/types';
};

export type GetReportsTypesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetReportsStatusesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports/statuses';
};

export type GetReportsStatusesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PatchReportsReportIdStatusData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query: {
        new_status: ReportStatus;
    };
    url: '/reports/{report_id}/status';
};

export type PatchReportsReportIdStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchReportsReportIdStatusError = PatchReportsReportIdStatusErrors[keyof PatchReportsReportIdStatusErrors];

export type PatchReportsReportIdStatusResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PatchReportsReportIdStatusResponse = PatchReportsReportIdStatusResponses[keyof PatchReportsReportIdStatusResponses];

export type DeleteReportsReportIdData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/reports/{report_id}';
};

export type DeleteReportsReportIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReportsReportIdError = DeleteReportsReportIdErrors[keyof DeleteReportsReportIdErrors];

export type DeleteReportsReportIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteReportsReportIdResponse = DeleteReportsReportIdResponses[keyof DeleteReportsReportIdResponses];

export type GetReportsReportIdData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/reports/{report_id}';
};

export type GetReportsReportIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportsReportIdError = GetReportsReportIdErrors[keyof GetReportsReportIdErrors];

export type GetReportsReportIdResponses = {
    /**
     * Successful Response
     */
    200: Report;
};

export type GetReportsReportIdResponse = GetReportsReportIdResponses[keyof GetReportsReportIdResponses];

export type PatchReportsReportIdData = {
    body: ReportEdit;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/reports/{report_id}';
};

export type PatchReportsReportIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchReportsReportIdError = PatchReportsReportIdErrors[keyof PatchReportsReportIdErrors];

export type PatchReportsReportIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PatchReportsReportIdResponse = PatchReportsReportIdResponses[keyof PatchReportsReportIdResponses];

export type GetReportsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Location Text
         */
        location_text: string;
    };
    url: '/reports/';
};

export type GetReportsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportsError = GetReportsErrors[keyof GetReportsErrors];

export type GetReportsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostReportsData = {
    body: ReportCreation;
    path?: never;
    query?: never;
    url: '/reports/';
};

export type PostReportsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostReportsError = PostReportsErrors[keyof PostReportsErrors];

export type PostReportsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};